---
files:
  - "**/*.md"

patterns:
  - name: markdown_code_block
    pattern: |
      /
          ^\s*```.*
          [\s\S]*?
          ^\s*```
      /gmx

languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - markdown_code_block

words:
  - combin
  - crdb
  - goroutine
  - goroutines
  - httpw
  - intspec
  - psql
