---
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dupword
    - err113
    - errcheck
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - iface
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - usetesting
    - wastedassign
    - whitespace
    - wsl
    - zerologlint

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow # causes too many false positives
      - fieldalignment # needs to be enabled in the future
  gci:
    sections:
      - standard
      - localmodule
      - default
    custom-order: true
  gocritic:
    enable-all: true
    disabled-checks:
      - unnamedResult # conflicts with nonamedreturns, named returns are more confusing
      - emptyStringTest # not more idiomatically
    settings:
      tooManyResultsChecker:
        maxResults: 6 # try to decrease in the future
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true # mnd is used instead
      - name: line-length-limit
        disabled: true # lll is used instead
      - name: cognitive-complexity
        disabled: true # gocognit, gocyclo, maintidx, nestif is used instead
      - name: function-result-limit
        disabled: true # gocritic is used instead
      - name: cyclomatic
        disabled: true # gocognit, gocyclo, maintidx, nestif is used instead
      - name: confusing-results
        disabled: true # conflicts with nonamedreturns, named returns are more confusing
      - name: unhandled-error
        arguments:
          - 'fmt\.Print.*' # error writing to stdout can only be reliably handled by panic
          - 'bytes\.Buffer\.Write.*' # always returns nil
      - name: flag-parameter
        disabled: true # causes too many false positives
      - name: confusing-naming
        disabled: true # needs to be enabled in the future
      - name: function-length
        disabled: true # needs to be enabled in the future
      - name: max-control-nesting
        arguments:
          - 6 # try to decrease in the future
      - name: max-public-structs
        arguments:
          - 8 # try to decrease in the future
      - name: argument-limit
        arguments:
          - 10 # try to decrease in the future

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
  show-stats: true

run:
  timeout: 10m
