name: Coverage
on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - run: |
          for dir in . v[0-9]*;
          do
            test "${dir}" == 'v[0-9]*' && continue

            cd "${dir}"

            coverfile="../coverage-${dir}"

            test "${dir}" == '.' && {
              coverfile="coverage-${dir}"
            }

            go test -v -coverprofile="${coverfile}" -covermode=atomic -timeout=1h ./...

            test "${dir}" != '.' && cd ..
          done
      - uses: coverallsapp/github-action@v2
        with:
          files: coverage-*
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
