---
name: Typos

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1
